### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by Mist3** [guzzle/retry-subscriber#34]
Problem 1
    - guzzlehttp/retry-subscriber 2.0.2 requires guzzlehttp/guzzle ~5.1 -> satisfiable by guzzlehttp/guzzle[5.1.0, 5.2.0, 5.3.0, 5.3.x-dev] but these conflict with your requirements or minimum-stability
    - guzzlehttp/retry-subscriber 2.0.1 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.x-dev] but these conflict with your requirements or minimum-stability
    - guzzlehttp/retry-subscriber 2.0.0 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.x-dev] but these conflict with your requirements or minimum-stability
    - Installation request for guzzlehttp/retry-subscriber ^2.0 -> satisfiable by guzzlehttp/retry-subscriber[2.0.0, 2.0.1, 2.0.2].

**Comment by GrahamCampbell** [comment]
I don't understand why you think this is a bug here?

**Comment by Mist3** [comment]
I am sorry, I should wrote something more then composer dump. I don't think it is a bug rather a issue. As I understand only way to make retry-subscriber work is to downgrade guzzle ?

**Comment by GrahamCampbell** [comment]
This package isn't needed in Guzzle 6. It already ships with this in the core.

**Comment by GrahamCampbell** [comment]
https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php

**Comment by Mist3** [comment]
Oh ok. Thank you for your time and advice.
