### ISSUE TITLE
Support for `guzzlehttp/guzzle` 6.*

### ISSUE THREAD

**Issue by SpacePossum** [guzzle/retry-subscriber#35]
Hi!

Any planning for supporting `guzzlehttp/guzzle` 6.*?

**Comment by Konafets** [comment]
@SpacePossum Does the [RetryMiddleware](https://github.com/guzzle/guzzle/blob/master/src/RetryMiddleware.php)  does not work for you?

Here is a tutorial about how to use it. https://addshore.com/2015/12/guzzle-6-retry-middleware/

**Comment by SpacePossum** [comment]
ah awesome, I'm going to use that :)
thanks so much @Konafets !
