### ISSUE TITLE
Does retry-subscriber work with Guzzle 3?

### ISSUE THREAD

**Issue by debraj-manna** [guzzle/retry-subscriber#36]
Does retry-subscriber work with Guzzle 3? Can the minimum Guzzle Version that retry-subscriber works with be added in README?

**Comment by Konafets** [comment]
To figure out a libs dependency you can have a look into the composer.json and according the the current version and the history of the composer.json the lib has never worked with Guzzle3.

**Comment by debraj-manna** [comment]
I am working on a very legacy code base which have been using Guzzle3.
